M48
; DRILL file KiCad 10.0.5 date 2026-09-05T09:08:25
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-05T09:08:25-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X17.11Y-61.895
X22.89Y-61.895
T2
X7.0Y-7.0
X7.0Y-63.0
X93.0Y-7.0
X93.0Y-63.0
M30
