M48
; DRILL file KiCad 10.0.5 date 2026-09-05T09:30:42
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-05T09:30:42-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X17.11Y-61.895
X22.89Y-61.895
T2
X4.5Y-4.5
X4.5Y-65.5
X95.5Y-4.5
X95.5Y-65.5
M30
